<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */


?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="field limiter js-toolbar-switch">
    <label class="label" for="limiter">
        <span><?= $block->escapeHtml(__('Show')) ?></span>
			<?php foreach ($block->getAvailableLimit() as $_key => $_limit):
				if ($block->isLimitCurrent($_key)): ?>
                <span class="current">
                    <?= $block->escapeHtml($_limit) ?>
                </span>
            <?php endif;
			endforeach; ?>
			<span class="limiter-text"><?= $block->escapeHtml(__('per page')) ?></span>
    </label>
	<div id="limiter" class="limiter-options js-toolbar-dropdown">
		<?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
			<div data-role="limiter" data-value="<?= $block->escapeHtmlAttr($_key) ?>"<?php if ($block->isLimitCurrent($_key)): ?>
				selected="selected"<?php endif ?>>
				<?= $block->escapeHtml($_limit) ?>
			</div>
		<?php endforeach; ?>
	</div>    
</div>
