<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block */
$wishlist_disabled = $this->helper('Olegnax\Athlete2\Helper\Helper')->getConfig('athlete2_settings/product/wishlist_disable');
if(!$wishlist_disabled):
$_helper = $this->helper( 'Olegnax\Athlete2\Helper\CssFiles' );
$theme_helper = $this->helper('Olegnax\Athlete2\Helper\Helper');
$actions_position = $theme_helper->getConfig('athlete2_settings/product/actions_position');
?>
<?php if ($block->isWishListAllowed()) : ?>
	<?php if ('2' == $actions_position) { ?>
    <a href="#"
       class="action towishlist athlete2-icon-heart a2-tooltip-btn"
       data-post='<?= /* @noEscape */ $block->getWishlistParams() ?>'
       data-action="add-to-wishlist"><span class="a2-tooltip"><?= $block->escapeHtml(__('Add to Wish List')) ?></span></a>
	<?php } else { ?>
    <a href="#"
       class="action towishlist athlete2-icon-heart"
       data-post='<?= /* @noEscape */ $block->getWishlistParams() ?>'
       data-action="add-to-wishlist"><span><?= $block->escapeHtml(__('Add to Wish List')) ?></span></a>
	<?php } ?>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= /* @noEscape */ $block->getWishlistOptionsJson() ?>
        }
    }
</script>
<?php endif; ?>