<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/

$actions_position = $this->helper('Olegnax\Athlete2\Helper\Helper')->getConfig('athlete2_settings/product/actions_position');
if ( '1' == $actions_position ||  !$actions_position ) {
?>
<div class="product-addto-links" data-role="add-to-links">
    <?= $block->getChildHtml() ?>
</div>
<?php } ?>