<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$product_mailtosocial = $this->helper('Olegnax\Athlete2\Helper\Helper')->getConfig('athlete2_settings/product/product_mailtosocial');
if ( !$product_mailtosocial ) :
?>
<?php $_product = $block->getProduct() ?>
<?php if ($block->canEmailToFriend()) :?>
    <a href="<?= $block->escapeUrl($this->helper(Magento\Catalog\Helper\Product::class)->getEmailToFriendUrl($_product)) ?>"
       class="action mailto friend"><span><?= $block->escapeHtml(__('Email')) ?></span></a>
<?php endif; ?>
<?php endif; ?>