<?php
$minicart_type = $this->helper('Olegnax\Athlete2\Helper\Helper')->getConfig( 'athlete2_settings/header/minicart_type' );

$icon = '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="19" height="17" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 18.9 17" style="enable-background:new 0 0 18.9 17;" xml:space="preserve">
<path d="M17.3,1.6C16.1,0.6,14.5,0,13,0.1c-1.3,0.2-2.6,0.8-3.5,1.8C8.3,0.9,7.2,0,5.9,0C4.3-0.1,2.8,0.5,1.7,1.6
	C0.6,2.7,0,4.3,0,5.9c0.1,1.3,0.5,2.5,1.3,3.5c0.4,0.5,4.2,4.4,6.4,6.6c0,0,0.8,1,1.7,1c0.8,0,1.7-1,1.7-1c2.4-2.4,6.5-6.5,6.9-7.3
	c0.5-0.8,0.9-1.8,0.9-2.8C19,4.3,18.4,2.8,17.3,1.6z M16.2,7.7l-6.8,7.1L3,8.3C2.4,7.6,2.1,6.8,2,5.9C2,4.8,2.4,3.8,3.1,3
	c0.8-0.7,1.8-1.1,2.8-1c1.3,0,3.5,2.5,3.5,2.5s2.4-2.4,3.5-2.4c1.1-0.1,2.1,0.3,2.9,1c0.7,0.8,1.1,1.8,1.1,2.8
	C16.8,6.5,16.6,7.2,16.2,7.7z"/>
</svg>';
?>

<div class=" header__item header__item-wishlist">
    <a class="button js-item-wishlist-action" data-bind="scope: 'wishlist'" aria-label="Wishlist">
		<i class="athlete2-icon-heart2"></i>
		<!-- ko if: wishlist().counter -->
        <span class="header__item-badge" data-bind="text: wishlist().counter.replace(/[^0-9]*/igm, '')"></span>
		<!-- /ko -->
    </a>
	<div class="header__item-dropdown-content"
			 data-role="OXmodal"
             data-mage-init='{"OXmodalWishlist":{
                "triggerTarget":".js-item-wishlist-action",
				"overlayClass":"ox-slideout-shadow",
                "timeout": "500",
                "closeOnEscape": true,
				"closeButtonTrigger":"#btn-wishllist-close",
                "closeOnMouseLeave": <?php echo 'dropdown-hover' == $minicart_type ? 'true' : 'false'; ?>,
				"hoverOpen": <?php echo 'dropdown-hover' == $minicart_type ? 'true' : 'false'; ?>,
				"type": "<?php echo 'slideout' == $minicart_type ? 'slideout' : ''; ?>",
				"positionSlideout": "right",
				"htmlClass":"ox-fixed"
			}}'>
		<div class="block block-wishlist" data-bind="scope: 'wishlist'">
			<div class="block-content">
				<!-- ko if: wishlist().counter -->
				<div class="items-total">
					<span data-bind="text: wishlist().counter" class="amount"></span>
					<span class="label">
						<?= $block->escapeHtml(__('in Wish list')) ?>
					</span>
					<button type="button" id="btn-wishllist-close" class="ox-overlay-close-btn" aria-label="Close Modal" data-action="close"><span></span></button>
				</div>
				<ol class="product-items no-display" id="wishlist-sidebar" data-bind="foreach: wishlist().items, css: {'no-display': null}">
					<li class="product-item">
						<div class="product-item-info">
							<a class="product-item-photo" data-bind="attr: { href: product_url, title: product_name }">
								<!-- ko template: {name: $data.image.template, data: $data.image} --><!-- /ko -->
							</a>
							<div class="product-item-details">
								<strong class="product-item-name">
									<a data-bind="attr: { href: product_url }" class="product-item-link">
										<span data-bind="text: product_name"></span>
									</a>
								</strong>
								<div data-bind="html: product_price"></div>
								<div class="product actions">
                                    <!-- ko if: product_is_saleable_and_visible -->
                                    <div class="actions-primary">
                                        <!-- ko if: product_has_required_options -->
                                        <a href="#" data-bind="attr: {'data-post': add_to_cart_params}" class="action tocart primary"><span><?= $block->escapeHtml(__('Add to Cart')) ?></span></a>
                                        <!-- /ko -->
                                        <!-- ko ifnot: product_has_required_options -->
                                            <button type="button" class="action tocart primary" data-bind="attr: {'data-post': add_to_cart_params}"><span><?= $block->escapeHtml(__('Add to Cart')) ?></span></button>
                                        <!-- /ko -->
                                    </div>
                                    <!-- /ko -->
									<div class="secondary">
										<a href="#"  data-bind="attr: {'data-post': delete_item_params}"
										   title="<?= $block->escapeHtmlAttr(__('Remove This Item')) ?>"
										   class="btn-remove action delete">
											<span><?= $block->escapeHtml(__('Remove This Item')) ?></span>
										</a>
									</div>
								</div>
							</div>
						</div>
					</li>
				</ol>
				<div class="dropdown-bottom-wrapper">
					<div class="subtotal">
						<span class="label">
							<?= $block->escapeHtml(__('Total Products')) ?>
						</span>
						<div class="amount" data-bind="text: wishlist().counter.replace(/[^0-9]*/igm, '')"></div>
					</div>
					<div class="dropdown-bottom-actions">
						<a class="action secondary details"
						   href="<?= $block->escapeUrl($this->helper('Magento\Wishlist\Helper\Data')->getListUrl()) ?>"
						   title="<?= $block->escapeHtmlAttr(__('View my Wishlist')) ?>"><span><?= $block->escapeHtml(__('View my Wishlist')) ?></span></a>
					</div>
				</div>
				<!-- /ko -->
				<!-- ko ifnot: wishlist().counter -->
				<div class="empty-wishlist-wrapper">
					<div class="athlete2-icon-heart empty-wishlist-icon"></div>
					<div class="subtitle empty"><?= $block->escapeHtml(__('You have no items in your wish list.')) ?></div>
					<button type="button" id="btn-wishllist-close" class="button continue primary" data-action="close"><span><?= $block->escapeHtml(__('Continue Shopping')) ?></span></button>
				</div>
				<!-- /ko -->
			</div>
		</div>
		<script type="text/x-magento-init">
			{
				"*": {
					"Magento_Ui/js/core/app": {
						"components": {
							"wishlist": {
								"component": "Magento_Wishlist/js/view/wishlist"
							}
						}
					}
				}
			}
		</script>

	</div>
</div>

